import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import { Navigation } from "@/components/navigation";
import  Footer from "@/components/footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Navigation />
          <main className="">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
